=== jpereztenerife/jpereztenerife.github.io/4/ejercicios/pedidos.dtd
<!ELEMENT pedido (sucursal, articulos)>
        <!ATTLIST pedido codigo_pedido CDATA #REQUIRED>
        <!ATTLIST pedido observaciones (urgente | incompleto) #IMPLIED>
    
    <!ELEMENT sucursal (nombre_sucursal, nombre_trabajador, direccion_exposicion, direccion_gestion?, fecha, observaciones?, plazo_revision)>
    <!ELEMENT nombre_sucursal (#PCDATA)>
    <!ELEMENT nombre_trabajador (#PCDATA)>
    <!ELEMENT direccion_exposicion (#PCDATA)>
    <!ELEMENT direccion_gestion (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT plazo_revision (#PCDATA)>

    <!ELEMENT articulos (articulo+)>
    <!ELEMENT articulo (numero_unidades, precio_unidad, observaciones_articulo?)>
        <!ATTLIST articulo codigo_articulo CDATA #REQUIRED>
    <!ELEMENT numero_unidades (#PCDATA)>
    <!ELEMENT precio_unidad (#PCDATA)>
    <!ELEMENT observaciones_articulo (#PCDATA)>

=== jpereztenerife/jpereztenerife.github.io/4/ejercicios/xml-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedido SYSTEM "pedidos.dtd">

<pedido codigo_pedido="T6574567" observaciones="urgente">
    <sucursal>
        <nombre_sucursal>Distanza Gran Vía</nombre_sucursal>
        <nombre_trabajador>Marco Polo</nombre_trabajador>
        <direccion_exposicion>Gran Vía 56</direccion_exposicion>
        <direccion_gestion>C/ de Hortaleza 12, 3ºB</direccion_gestion>
        <fecha>06/05/2017</fecha>
        <plazo_revision></plazo_revision>
    </sucursal>

    <articulos>
        <articulo codigo_articulo="BCH-426">
            <numero_unidades>12</numero_unidades>
            <precio_unidad>28,75€</precio_unidad>
            <observaciones_articulo>Enviar unidad de exposición</observaciones_articulo>
        </articulo>
        <articulo codigo_articulo="CTF-664">
            <numero_unidades>6</numero_unidades>
            <precio_unidad>42,50€</precio_unidad>
        </articulo>
        <articulo codigo_articulo="TAB-432">
            <numero_unidades>25</numero_unidades>
            <precio_unidad>19,80€</precio_unidad>
            <observaciones_articulo>Enviar en toda la gama de colores</observaciones_articulo>
        </articulo>
        <articulo codigo_articulo="PIP-828">
            <numero_unidades>4</numero_unidades>
            <precio_unidad>87,50€</precio_unidad>
        </articulo>
    </articulos>
</pedido>
